# 1.Create a 3×3×3 array with random values

In [1]:
import numpy as np

# Set the random seed for reproducibility
np.random.seed(0)

# Create a 3x3x3 array with random values between 0 and 1
array = np.random.rand(3, 3, 3)

print(array)

[[[0.5488135  0.71518937 0.60276338]
  [0.54488318 0.4236548  0.64589411]
  [0.43758721 0.891773   0.96366276]]

 [[0.38344152 0.79172504 0.52889492]
  [0.56804456 0.92559664 0.07103606]
  [0.0871293  0.0202184  0.83261985]]

 [[0.77815675 0.87001215 0.97861834]
  [0.79915856 0.46147936 0.78052918]
  [0.11827443 0.63992102 0.14335329]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
import numpy as np

# Create a 5x5 matrix with all zeros
matrix = np.zeros((5, 5))

# Set the values 1, 2, 3, 4 just below the diagonal
np.fill_diagonal(matrix[1:], [1, 2, 3, 4])

print(matrix)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern 

In [4]:
import numpy as np

# Create an 8x8 matrix with all zeros
matrix = np.zeros((8, 8))

# Fill the matrix with a checkerboard pattern
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1

print(matrix)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# 4. Normalize a 5x5 random matrix

In [5]:
import numpy as np

# Create a 5x5 random matrix
matrix = np.random.random((5, 5))

# Normalize the matrix
normalized_matrix = (matrix - np.mean(matrix)) / np.std(matrix)

print(normalized_matrix)

[[ 1.87733962  0.11528392 -0.33140287 -0.95695354  1.16707062]
 [-0.15850481  0.30942411 -1.98115401  0.51446585  0.49137948]
 [ 0.51154243  1.87350213  0.78194855 -0.56125092 -0.23817843]
 [ 0.84783863 -1.80847566  0.71921449  0.73534707 -1.18271344]
 [-1.52217295 -0.74494732 -0.54373594  0.31677047 -0.23163748]]


# 5. How to find common values between two arrays?

In [13]:
import numpy as np

# Create two arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([4, 5, 6, 7, 8])

# Find common values
common_values = np.intersect1d(array1, array2)

print(common_values)

[4 5]


# 6. How to get the dates of yesterday, today and tomorrow? 

In [9]:
from datetime import date, timedelta

# Get today's date
today = date.today()

# Get yesterday's date
yesterday = today - timedelta(days=1)

# Get tomorrow's date
tomorrow = today + timedelta(days=1)

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

Yesterday: 2023-09-20
Today: 2023-09-21
Tomorrow: 2023-09-22


# 7. Consider two random array A and B, check if they are equal

In [11]:
import numpy as np

# Create two random arrays A and B
A = np.random.rand(5)
B = np.random.rand(5)

# Check if A and B are equal
are_equal = np.array_equal(A, B)

print("Array A:", A)
print("Array B:", B)
print("Are A and B equal?", are_equal)

Array A: [0.98837384 0.10204481 0.20887676 0.16130952 0.65310833]
Array B: [0.2532916  0.46631077 0.24442559 0.15896958 0.11037514]
Are A and B equal? False


# 8.Create random vector of size 10 and replace the maximum value by 0

In [15]:
import numpy as np

# Create a random vector of size 10
vector = np.random.rand(10)

# Find the maximum value in the vector
max_value = np.max(vector)

# Find the index of the maximum value
max_index = np.argmax(vector)

# Replace the maximum value with 0
vector[max_index] = 0

print("Original vector:", vector)
print("Maximum value:", max_value)
print("Index of maximum value:", max_index)


Original vector: [0.65632959 0.13818295 0.19658236 0.36872517 0.82099323 0.09710128
 0.83794491 0.09609841 0.         0.4686512 ]
Maximum value: 0.9764594650133958
Index of maximum value: 8


# 9 How to print all the values of an array?

In [17]:
import numpy as np

# Create an array
array = np.array([1, 2, 3, 4, 5, 6])

# Print all the values of the array
print(array)


[1 2 3 4 5 6]


# 10.Subtract the mean of each row of a matrix

In [19]:
import numpy as np

# Create a matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Calculate the mean of each row
row_means = np.mean(matrix, axis=1)

# Subtract the mean of each row from the corresponding row
matrix_minus_mean = matrix - row_means[:, np.newaxis]

# Print the resulting matrix
print(matrix_minus_mean)

[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [21]:
import numpy as np

# Given vector
given_vector = np.array([4, 5, 6, 7, 8])

# Second vector with indices
indices_vector = np.array([0, 1, 3, 1])

# Add 1 to each element indexed by the second vector
given_vector[indices_vector] += 1

print(given_vector)

[5 6 6 8 8]


# 12. How to get the diagonal of a dot product?

In [27]:
import numpy as np

# Define two matrices
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

matrix2 = np.array([[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]])

# Calculate the dot product of the two matrices
dot_product = np.dot(matrix1, matrix2)

# Get the diagonal of the dot product
diagonal = np.diagonal(dot_product)

print(diagonal)

[ 84 216 366]


# 13.How to find the most frequent value in an array?

In [4]:
my_array = np.random.randint(0,10,50)
print(my_array)
 # Find the most frequent value
most_frequent_value = np.bincount(my_array).argmax()

print("Most frequent value:", most_frequent_value)

[1 0 0 7 1 8 2 0 5 9 0 8 9 8 0 8 8 6 6 6 3 2 8 0 1 1 6 7 1 3 7 7 9 2 6 9 8
 9 6 7 7 1 2 2 0 1 0 6 4 0]
Most frequent value: 0


In [ ]:
14.How to get the n largest values of an array

In [3]:
import numpy as np

# Example array
arr = np.array([5, 10, 3, 8, 1, 6])

# Get the indices that would sort the array in descending order
sorted_indices = np.argsort(-arr)

# Get the n largest values
n = 3
n_largest_values = arr[sorted_indices[:n]]

print(n_largest_values)



[10  8  6]


# 15.How to create a record array from a regular array?

In [7]:
import numpy as np

# Regular array
regular_array = np.array([(1, 'John', 25), (2, 'Jane', 30), (3, 'Mike', 35)])

# Create a record array
record_array = np.rec.array(regular_array, dtype=[('id', int), ('name', 'U10'), ('age', int)])

print(record_array)

ValueError: When changing to a larger dtype, its size must be a divisor of the total size in bytes of the last axis of the array.

# 16. How to swap two rows of an array?

In [8]:
import numpy as np

# Create a 2D array
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Swap rows
array[[0, 2]] = array[[2, 0]]

print(array)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


# 17. Write python code to reshape to the next dimension of numpy array?

In [5]:
# Create a 1D NumPy array
arr_1d = np.array([1, 2, 3, 4, 5, 6])

# Reshape to the next dimension (2D)
arr_2d = arr_1d.reshape((2, -1))  # -1 automatically calculates the size of the second dimension

# Print the original and reshaped arrays
print("Original 1D Array:")
print(arr_1d)

print("\nReshaped 2D Array:")
print(arr_2d)

Original 1D Array:
[1 2 3 4 5 6]

Reshaped 2D Array:
[[1 2 3]
 [4 5 6]]
